export const CA = "0xcE5e33c6f131fAD365Eb9561cC339DFD2a884F16"
export const ABI = [
  { inputs: [], stateMutability: "nonpayable", type: "constructor" },
  { inputs: [], name: "AccessControlBadConfirmation", type: "error" },
  {
    inputs: [
      { internalType: "address", name: "account", type: "address" },
      { internalType: "bytes32", name: "neededRole", type: "bytes32" },
    ],
    name: "AccessControlUnauthorizedAccount",
    type: "error",
  },
  { inputs: [], name: "CannotPause", type: "error" },
  { inputs: [], name: "EnforcedPause", type: "error" },
  { inputs: [], name: "ExceedsCapacity", type: "error" },
  { inputs: [], name: "ExpectedPause", type: "error" },
  { inputs: [], name: "InsufficientFunds", type: "error" },
  { inputs: [], name: "InvalidDiscount", type: "error" },
  { inputs: [], name: "InvalidInitialization", type: "error" },
  { inputs: [], name: "InvalidRarityPercentage", type: "error" },
  { inputs: [], name: "InvalidSignature", type: "error" },
  { inputs: [], name: "NoDeploymentNFT", type: "error" },
  { inputs: [], name: "NotInitializing", type: "error" },
  {
    inputs: [
      { internalType: "address", name: "have", type: "address" },
      { internalType: "address", name: "want", type: "address" },
    ],
    name: "OnlyCoordinatorCanFulfill",
    type: "error",
  },
  { inputs: [], name: "OutOfStock", type: "error" },
  { inputs: [], name: "Reentrancy", type: "error" },
  { inputs: [{ internalType: "bool", name: "claimed", type: "bool" }], name: "ReqIdInvalid", type: "error" },
  { inputs: [{ internalType: "uint256", name: "balance", type: "uint256" }], name: "WithdrawFailed", type: "error" },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: "uint64", name: "costGwei", type: "uint64" }],
    name: "CostGweiChanged",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: "address", name: "", type: "address" }],
    name: "DeployedNFT",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: "uint8", name: "discount", type: "uint8" }],
    name: "DiscountGachaTenChanged",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "who", type: "address" },
      { indexed: false, internalType: "uint256", name: "requestId", type: "uint256" },
    ],
    name: "GachaOne",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "who", type: "address" },
      { indexed: false, internalType: "uint256", name: "requestId", type: "uint256" },
    ],
    name: "GachaTen",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: "bool", name: "guarantee", type: "bool" }],
    name: "GuaranteeChanged",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: "enum GachaPool.Rarity", name: "level", type: "uint8" }],
    name: "GuaranteeRarityChanged",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "requestId", type: "uint256" },
      { indexed: false, internalType: "enum GachaPool.Rarity", name: "", type: "uint8" },
    ],
    name: "Guaranteed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: "uint64", name: "version", type: "uint64" }],
    name: "Initialized",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "requestId", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "count", type: "uint256" },
    ],
    name: "NftMinted",
    type: "event",
  },
  { anonymous: false, inputs: [], name: "NftUriChanged", type: "event" },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: "address", name: "account", type: "address" }],
    name: "Paused",
    type: "event",
  },
  { anonymous: false, inputs: [], name: "PercentageChanged", type: "event" },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "requestId", type: "uint256" },
      { indexed: false, internalType: "uint256[]", name: "randomWords", type: "uint256[]" },
    ],
    name: "RandomFulfilled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: "uint256", name: "requestId", type: "uint256" }],
    name: "RandomRequested",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "bytes32", name: "role", type: "bytes32" },
      { indexed: true, internalType: "bytes32", name: "previousAdminRole", type: "bytes32" },
      { indexed: true, internalType: "bytes32", name: "newAdminRole", type: "bytes32" },
    ],
    name: "RoleAdminChanged",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "bytes32", name: "role", type: "bytes32" },
      { indexed: true, internalType: "address", name: "account", type: "address" },
      { indexed: true, internalType: "address", name: "sender", type: "address" },
    ],
    name: "RoleGranted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "bytes32", name: "role", type: "bytes32" },
      { indexed: true, internalType: "address", name: "account", type: "address" },
      { indexed: true, internalType: "address", name: "sender", type: "address" },
    ],
    name: "RoleRevoked",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: "address", name: "account", type: "address" }],
    name: "Unpaused",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "withdrawer", type: "address" },
      { indexed: false, internalType: "uint256", name: "value", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "timestamp", type: "uint256" },
    ],
    name: "Withdraw",
    type: "event",
  },
  {
    inputs: [],
    name: "DEFAULT_ADMIN_ROLE",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "GACHA_CARD_NFT",
    outputs: [{ internalType: "contract GachaCardNFT", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "reqId", type: "uint256" },
      { internalType: "bytes", name: "signature", type: "bytes" },
    ],
    name: "claim",
    outputs: [{ internalType: "uint256", name: "count", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "claimSigner",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "string", name: "name", type: "string" },
      { internalType: "string", name: "symbol", type: "string" },
    ],
    name: "deployGachaCardNFT",
    outputs: [{ internalType: "address", name: "deployed", type: "address" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  { inputs: [], name: "gachaOne", outputs: [], stateMutability: "payable", type: "function" },
  { inputs: [], name: "gachaTen", outputs: [], stateMutability: "payable", type: "function" },
  {
    inputs: [],
    name: "getAddressVRF",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "reqId", type: "uint256" }],
    name: "getPlayer",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getPlayersCount",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getPoolConfig",
    outputs: [
      { internalType: "uint64", name: "costGwei", type: "uint64" },
      { internalType: "uint32", name: "poolId", type: "uint32" },
      { internalType: "uint32", name: "supply", type: "uint32" },
      { internalType: "uint8", name: "discountGachaTen", type: "uint8" },
      { internalType: "bool", name: "guarantee", type: "bool" },
      { internalType: "enum GachaPool.Rarity", name: "guaranteeRarity", type: "uint8" },
      { internalType: "uint8[5]", name: "percentages", type: "uint8[5]" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getRemaining",
    outputs: [{ internalType: "uint32", name: "", type: "uint32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "by", type: "address" }],
    name: "getRequests",
    outputs: [{ internalType: "uint256[]", name: "", type: "uint256[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "reqId", type: "uint256" }],
    name: "getResult",
    outputs: [
      { internalType: "uint8", name: "", type: "uint8" },
      { internalType: "uint256[]", name: "", type: "uint256[]" },
      { internalType: "enum GachaPool.Rarity[]", name: "", type: "uint8[]" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "role", type: "bytes32" }],
    name: "getRoleAdmin",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "role", type: "bytes32" },
      { internalType: "address", name: "account", type: "address" },
    ],
    name: "grantRole",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "role", type: "bytes32" },
      { internalType: "address", name: "account", type: "address" },
    ],
    name: "hasRole",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_subId", type: "uint256" },
      { internalType: "address", name: "_vrfCoordinator", type: "address" },
      { internalType: "bytes32", name: "_keyHash", type: "bytes32" },
      { internalType: "address", name: "_admin", type: "address" },
      { internalType: "address", name: "_signer", type: "address" },
      {
        components: [
          { internalType: "uint64", name: "costGwei", type: "uint64" },
          { internalType: "uint32", name: "poolId", type: "uint32" },
          { internalType: "uint32", name: "supply", type: "uint32" },
          { internalType: "uint8", name: "discountGachaTen", type: "uint8" },
          { internalType: "bool", name: "guarantee", type: "bool" },
          { internalType: "uint8[5]", name: "percentages", type: "uint8[5]" },
          { internalType: "enum GachaPool.Rarity", name: "guaranteeRarity", type: "uint8" },
        ],
        internalType: "struct GachaPool.PoolConfig",
        name: "_initConfig",
        type: "tuple",
      },
    ],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  { inputs: [], name: "pause", outputs: [], stateMutability: "nonpayable", type: "function" },
  {
    inputs: [],
    name: "paused",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "requestId", type: "uint256" },
      { internalType: "uint256[]", name: "randomWords", type: "uint256[]" },
    ],
    name: "rawFulfillRandomWords",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "role", type: "bytes32" },
      { internalType: "address", name: "callerConfirmation", type: "address" },
    ],
    name: "renounceRole",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "role", type: "bytes32" },
      { internalType: "address", name: "account", type: "address" },
    ],
    name: "revokeRole",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint64", name: "_cost", type: "uint64" }],
    name: "setCostGwei",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint8", name: "_discount", type: "uint8" }],
    name: "setDiscountGachaTen",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bool", name: "_guarantee", type: "bool" }],
    name: "setGuarantee",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "enum GachaPool.Rarity", name: "_level", type: "uint8" }],
    name: "setGuaranteeRarity",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "string", name: "baseURI", type: "string" },
      { internalType: "string", name: "contractURI", type: "string" },
    ],
    name: "setNftUri",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint8[5]", name: "_percentages", type: "uint8[5]" }],
    name: "setPercentage",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes4", name: "interfaceId", type: "bytes4" }],
    name: "supportsInterface",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  { inputs: [], name: "unpause", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [], name: "withdraw", outputs: [], stateMutability: "nonpayable", type: "function" },
] as const
